version: '3.8'

services:

  # base de donnees auth
  auth_db:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  # base de donnees planning
  planning_db:
    image: postgres:15
    environment:
      POSTGRES_DB: planning_db
      POSTGRES_USER: planning_user
      POSTGRES_PASSWORD: planning_pass
    volumes:
      - planning_db_data:/var/lib/postgresql/data

  # base de donnees emargement
  emarg_db:
    image: postgres:15
    environment:
      POSTGRES_DB: emarg_db
      POSTGRES_USER: emarg_user
      POSTGRES_PASSWORD: emarg_pass
    volumes:
      - emarg_db_data:/var/lib/postgresql/data

  # service authentification
  auth_service:
    build: ./auth_service
    environment:
      DATABASE_URL: postgresql://auth_user:auth_pass@auth_db:5432/auth_db
      SECRET_KEY: monsecretjwt123
    ports:
      - "5001:5001"
    depends_on:
      - auth_db

  # service planning (classes, promotions, etudiants)
  planning_service:
    build: ./planning_service
    environment:
      DATABASE_URL: postgresql://planning_user:planning_pass@planning_db:5432/planning_db
      SECRET_KEY: monsecretjwt123
    ports:
      - "5002:5002"
    depends_on:
      - planning_db

  # service emargement (feuilles de presence)
  emargement_service:
    build: ./emargement_service
    environment:
      DATABASE_URL: postgresql://emarg_user:emarg_pass@emarg_db:5432/emarg_db
      SECRET_KEY: monsecretjwt123
      PLANNING_SERVICE_URL: http://planning_service:5002
    ports:
      - "5003:5003"
    depends_on:
      - emarg_db
      - planning_service

  # interface web
  frontend:
    build: ./frontend
    environment:
      SECRET_KEY: monsecretjwt123
      AUTH_SERVICE_URL: http://auth_service:5001
      PLANNING_SERVICE_URL: http://planning_service:5002
      EMARG_SERVICE_URL: http://emargement_service:5003
    ports:
      - "5000:5000"
    depends_on:
      - auth_service
      - planning_service
      - emargement_service

volumes:
  auth_db_data:
  planning_db_data:
  emarg_db_data:
